### ISSUE TITLE
b3-curves-di1

### ISSUE THREAD

**Issue by Parau** [wilsonfreitas/brasa#3]
Estava lendo o texto o artigo "QuantLib, dez anos depois …" (https://www.wilsonfreitas.net/posts/2023-07-19-quantlib/quantlib.html) que utiliza os dados deste projeto.
Agora que não existe mais o servidor de download o caminho para gerar o histórico é coletar diariamente os dados da página   url: https://www2.bmf.com.br/pages/portal/bmfbovespa/lumis/lum-ajustes-do-pregao-ptBR.asp?

Obrigado

**Comment by wilsonfreitas** [comment]
Sim, essa página entrega os preços dos contratos futuros de forma simples, por isso gosto de pegar dela, entretanto ela não traz informações importantes como vencimento, por exemplo.
Para alguns contratos a regra é meio chata para implementar, como no caso do WIN.

Para informações mais completas uso a página

https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/historico/boletins-diarios/pesquisa-por-pregao/pesquisa-por-pregao/

Contudo, o histórico é bem menor, começando em 2018.
